name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull jairogloz/go-budget:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f go-budget-container || true
      - name: Run Docker Container
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
          MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
        run: sudo docker run -d --name go-budget-container -p 8080:8080 \
          -e GO_BUDGET_MONGO_URI="$MONGO_URI" \
          -e GO_BUDGET_MONGO_DB_NAME="$MONGO_DB_NAME" \
          jairogloz/go-budget:latest
